version: "2.2"

services:
  backend:
    image: lecafard/when3meet_backend
    build: ./backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - POSTGRES_CONNECTION=postgres://when3meet:${POSTGRES_PASSWORD}@postgres/when3meet
  frontend:
    image: lecafard/when3meet_frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - backend
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=when3meet
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=when3meet
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
